server:
  port: 9090
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: false
    use_sql_comments: false
    format_sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
logging:
  level:
    org.springframework.web: DEBUG
