spring:
  profiles:
    active: dev
  datasource:
    url: 
    username:
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties.mail:
      transport.protocol: smtp
      smtp.auth: true
      smtp.starttls.enable: true
      smtp.starttls.required: true
    sender.admin:
security:
  jwt:
    token:
      secretKey:
      tokenPrefix: Bearer
      expirationLength: 3600000
  user:
    invalid-cred-limit: 5
logging:
  level:
    org.springframework.web: INFO
