spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://192.168.0.123:3306/kitchen_table
    username: admin
    password: password
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create
security:
  jwt:
    token:
      secretKey: secret
      tokenPrefix: Bearer
      expirationLength: 3600000
logging:
  level:
    org.springframework.web: INFO
