spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://192.168.0.140:3307/kitchen_fridge
    username: kitchen_admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: kozman31@gmail.com
    password: hjbfjxkgmlvkltiw
    properties.mail:
      transport.protocol: smtp
      smtp.auth: true
      smtp.starttls.enable: true
      smtp.starttls.required: true
    sender.admin: kozman31@gmail.com
security:
  jwt:
    token:
      secretKey: secret
      tokenPrefix: Bearer
      expirationLength: 3600000
  user:
    invalid-cred-limit: 5
logging:
  level:
    org.springframework.web: INFO
